# -*- coding: utf-8 -*-
"""Tugas5_DDP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RqMgN3xGG1APs47mDSIN4NTbvhSbW1LZ
"""

namaKendaraan = "Astrea"
jenisKendaraan = "Motor"
ccKendaraan = 250
warnaKendaraan = "Hijau"
rodaKendaraan = 2
data_kendaraan = [
    namaKendaraan, jenisKendaraan, ccKendaraan,
    warnaKendaraan, rodaKendaraan
]
print(data_kendaraan)

hargaKendaraan = 12000
tipeKendaraan = "Kopling"

data_kendaraan.append(hargaKendaraan)
data_kendaraan.append(tipeKendaraan)
print(data_kendaraan)

merkKendaraan = "Yamaha"
data_kendaraan.insert(2, merkKendaraan)
print(data_kendaraan)

pilihan = input("""
Silahkan pilih menu yang di inginkan
====================================
1. Luas Persegi
2. Luas Lingkaran
3. Luas Segitiga
====================================
Kirimkan hanya angka saja,
jawaban = """)

print(type(pilihan))
match pilihan:
  case "1":
    sisi = int(input("sisi = "))
    luas = sisi * sisi

    print(f"luas persegi dengan sisi {sisi} adalah {luas}")
    # luas persegi
  case "2":
    # luas lingkaran
    # phi * jarjjari**2
    jarijari = int(input("jarijari = "))
    luas = 3.14 * jarijari**2

    print(f"luas lingkaran dengan jarijari {jarijari} adalah {luas}")

    print( "")
  case "3":
    # luas segitiga
    # (alas * tinggi)/2

    alas = float(input("masukan alas segitiga = "))
    tinggi = float(input("masukan tinggi segitiga = "))

    luassegitiga = 0.5 * alas * tinggi
    print ("luas segitiga", luassegitiga)

  case _:
    print("yaa tidak ada")